### ISSUE TITLE
No Response when Laptop Opens after Closing

### ISSUE THREAD

**Issue by zzuum** [KaOSx/main#10]
When I close my laptop lid and open it back up, I am greeted with no response from the OS and a black screen. I can hear the computer running in the background but there is not response. I am running an HP G6 laptop with an AMD A6-3400M APU with HD 6520G graphics. Kingston 120GB SSD. 8GB Ram.

**Comment by demmm** [comment]
More info needed:
http://kaosx.us/asking-and-reporting-the-smart-way/

Especially system journalctl logs (besides the first point, that whole log is need too)

**Comment by demmm** [comment]
Since help is asked for in the forum, issues are not a place for user support.
Closing.  Please re-open if you found it actually is a bug.
