### ISSUE TITLE
Misspelling on Installer Slideshow Slide ("approximately")

### ISSUE THREAD

**Issue by puffybsd** [KaOSx/main#11]
On one of the installer's slideshow slides ("QT5" + "KDE" +..."), "approximately" is spelled "approximatley". 
Extremely minor, insignificant defect, but it's such an excellent and polished first impression otherwise.  (Took a screenshot, but qupzilla freezes on github's file uploader modal.)

Keep up the excellent work - enjoying the distro.

**Comment by demmm** [comment]
Thanks for reporting, though not at all a main package issue......
Fixed in calamares git:
https://github.com/KaOSx/calamares/commit/b18aeb566170bf6209bd633fa0c9f05e1a36dffc

**Comment by puffybsd** [comment]
Just saw the installer repo today, sorry about that. Thanks for correcting.

**Comment by demmm** [comment]
Qupzilla hang should be fixed too, upstream bug, patched frameworks for it today:
https://github.com/KaOSx/apps/commit/d2d804ff1a6313be838c1479d97b3e372dc4e5d0
