### ISSUE TITLE
postgresql fails to start

### ISSUE THREAD

**Issue by JantarMantar** [KaOSx/main#16]
postgresql.service when started with systemctl exits with error code 1. The command that fails is /usr/bin/postgresql-check-db-dir. 

I believe the root cause for this failure is, outdated postgresql-check-db-dir script which is trying to verify the database version to be 9.3, whereas the postgresql is more recent and creates  databases with versions 9.4

**Comment by demmm** [comment]
You can check if that is the issue by editing /usr/bin/postgresql-check-db-dir and set to 9.4 and 9.3 (from 9.3 and 9.2)
Rebuild will be up in the [build] repo shortly, but no need to get it from there right away, if manually editing fixes it.

**Comment by JantarMantar** [comment]
The script postgresql-check-db-dir from the build repo correctly checks the database version. systemd is now able to start postgres service without any failures.

- Thank
