### ISSUE TITLE
module intel_pstate not found but compilation FLAGS is set

### ISSUE THREAD

**Issue by FiloSpaTeam** [KaOSx/main#18]
With newest Intel CPU, to enable Boost and other features i need intel_pstate module.
With right command shell i found that the flag is enabled.
Why no module can be loaded with modprobe?
![screenshot_20151230_013405](https://cloud.githubusercontent.com/assets/2974561/12044647/8649954c-ae95-11e5-856f-50b493ae0730.png)

**Comment by demmm** [comment]
See this thread to understand more about intel_state:
https://plus.google.com/+TheodoreTso/posts/2vEekAsG2QT

Basically, when you have an intel processor that can use intel_psate, it is automatically loaded for you.
It is build into the KaOS kernel:
https://github.com/KaOSx/core/blob/master/linux/config#L657

What exactly is this bug report about?  Looks more like you are looking for help then actually reporting a bug.
If so, please use the forum, IRC channel, gitter or G+ for help.

**Comment by FiloSpaTeam** [comment]
Help is always appreciated but.
Here is the problem. Look this:
```bash
[root@claudio-ge72-6qd claudiom]# modprobe intel_pstate
modprobe: FATAL: Module intel_pstate not found in directory /lib/modules/4.2.6-1
[root@claudio-ge72-6qd claudiom]# modprobe acpi-cpufreq
```
And my CPU cannot enable Boost state.

**Comment by demmm** [comment]
Again, read what I linked you, this is not a user controlled module.

**Comment by FiloSpaTeam** [comment]
Ok understand that.
I have thought that this module need to be present in that folder.

I'll try to disable that module and use acpi-cpufreq. Thanks
