### ISSUE TITLE
Add clang-tools-extra to llvm PKGBUILD

### ISSUE THREAD

**Issue by FiloSpaTeam** [KaOSx/main#19]
To add clang-tools-extra, the sources need to be in the same directory of llvm during building. Create a KCP repo is not usefull, it's more simple add sources in this package like Archlinux source files.

**Comment by demmm** [comment]
There is zero need in the KaOS repos for this, get the KaOS llvm PKGBUILD and adjust to your needs, build with the same versions.
Please do not keep opening bug reports for packages you would like to have, these are not bugs, KaOS has a clear statement all over the website that it's repos will stay limited in size.

**Comment by FiloSpaTeam** [comment]
A question. About features where anyone can write something? I have read guidelines but i don t understand where to find a place to write questions about packages.

**Comment by demmm** [comment]
Best place is the forum section:
http://kaosx.us/phpBB3/viewforum.php?f=9
IRC is always an option (kaosx channel on freenode)
