### ISSUE TITLE
vlc error upgrade

### ISSUE THREAD

**Issue by FiloSpaTeam** [KaOSx/main#20]
```
/tmp/alpm_UTod3T/.INSTALL: riga 1:  2359 Errore di segmentazione usr/lib/vlc/vlc-cache-gen -f /usr/lib/vlc/plugins
```

During upgrade with ```pacman -Syyu```

**Comment by demmm** [comment]
Can't reproduce (5 systems updated)
What happens on your install when you just run ```/usr/lib/vlc/vlc-cache-gen -f /usr/lib/vlc/plugins``` 
Did you install the svn version ever of clang/llvm?  That would explain major parts of your install being broken.

**Comment by FiloSpaTeam** [comment]
those errors are present before the clang/llvm-svn. I'm telling now only because i expected solution from system upgrade.

**Comment by FiloSpaTeam** [comment]
```Segmentation error```

**Comment by demmm** [comment]
so vlc itself does not run for you either?

**Comment by FiloSpaTeam** [comment]
vlc run correctly, only problem with fullscreen but i think it's related to hybrid graphics

**Comment by demmm** [comment]
then it looks like you have a corrupted plugins cache, remove it and generate again
```sudo rm -f usr/lib/vlc/plugins/plugins-*.dat```
```/usr/lib/vlc/vlc-cache-gen -f /usr/lib/vlc/plugins```

**Comment by FiloSpaTeam** [comment]
no nothing :(
```
[root@claudio-ge72-6qd thinks]# rm -f usr/lib/vlc/plugins/plugins-*.dat
[root@claudio-ge72-6qd thinks]# /usr/lib/vlc/vlc-cache-gen -f /usr/lib/vlc/plugins
Errore di segmentazione
```

**Comment by FiloSpaTeam** [comment]
It's not a new post but seems that fluidsynth is the problem.
Can be?

https://bbs.archlinux.org/viewtopic.php?id=162848

**Comment by FiloSpaTeam** [comment]
https://bugs.archlinux.org/task/39676

**Comment by demmm** [comment]
Again, so far no-one can reproduce your issue, so if it was a repo package, all should be effected.
As stands now, this is a local issue, until it is clear anyone can reproduce.

**Comment by demmm** [comment]
Go to Octopi, tools, SysInfo and paste the output link here

**Comment by FiloSpaTeam** [comment]
https://gist.github.com/456610001a1f6acaaf50

**Comment by demmm** [comment]
This log shows installing so many packages that are not compatible with your KaOS install, that a bug reports for such installs are no longer valid.  For one you have a complete incompatible llvm version.

**Comment by FiloSpaTeam** [comment]
I removed llvm libs but nothing. There is nothing that can revert situation?
