### ISSUE TITLE
plasma crashes on boot with Nvidia-nonfree

### ISSUE THREAD

**Issue by RomuloPBenedetti** [KaOSx/main#22]
... And I have some problems that make nvidia-nonfree the only alternative:

1. My machine dedicates HDMI to nvidia, its the only way to conect to my secondary display.
2. KaOS can't detect my secondary monitor automatically with prime, I need to go to terminal and in the end I get a reduced resolution detection (my secondary display is ultra-wide) with mouse pointer glitches constantly appearing.

I'm not sure, but it appears to be a problem with drive version and my 525M Nvidia gpu, I have a Kubuntu working installation with 352.63.

If someone has some Idea I would be glad. :)

**Comment by demmm** [comment]
For hybrid systems, you need to either use nouveau or nvidia-bumblebee:
http://kaosx.us/hybrid-graphic-systems/

**Comment by RomuloPBenedetti** [comment]
I don't mind losing intel, I need nvidia,

**Comment by demmm** [comment]
Read the link posted for you, it gives you nvidia-bumblebee

**Comment by RomuloPBenedetti** [comment]
I need a solution that can put xorg/plasma to run over Nvidia on boot, and so made hdmi monitor accessible. bumblebee  run apps over a intel session witch did not have access to hdmi.

**Comment by demmm** [comment]
Read the bumblebee/bbswitch wiki to set nvidia as default

**Comment by RomuloPBenedetti** [comment]
I can only find atempts to remove bumblebee and use nvidia...

> Set system to use NVIDIA card exclusively, test DP/Monitor combination and generate xorg.nvidia.conf. This step is not required, but recommended if your system Bios has an option to switch the graphics into NVIDIA-only mode. To do this, first uninstall the bumblebee package and install just the NVIDIA driver. Then reboot, enter the Bios and switch the Graphics to NVIDIA-only. When back in Arch, connect you Monitor on DP and use startx to test if it is working in principle. Use Xorg -configure to generate an xorg.conf file for your NVIDIA card. This will come in handy further down below.

from [archwiki](https://wiki.archlinux.org/index.php/bumblebee#Output_wired_to_the_NVIDIA_chip)

**Comment by demmm** [comment]
This is not Arch, that wiki does not apply, use the link as added in the previous link I posted, it lists the needed wiki.
Example https://github.com/Bumblebee-Project/bbswitch

**Comment by demmm** [comment]
Unless you have nvidia-bumblebee and bbswitch installed and can show a bug then, this bug report is invalid, needed packages not installed for system.

closing
