### ISSUE TITLE
Plasma panel freezes after cca 10 minutes if there is no user activity

### ISSUE THREAD

**Issue by AdamSadovsky** [KaOSx/main#23]
This problem starts after clean installation of KaOS-2016.03. If I disable sleep mode and also disable display going to blank - it stills freezes. It is possible to change opened windows by alt+tab and to invoke logout popup by ctrl+alt+del. There is no dual-screen scenario.

[https://gist.github.com/4bbb0da09ff4600a1dbc](https://gist.github.com/4bbb0da09ff4600a1dbc)

**Comment by demmm** [comment]
Can you reproduce in Live mode (no changes, just let it boot and idle for the required 10 minutes)?
Can you reproduce right after a clean install, no updates, no packages extra, no theme changes or widgets added?
Try to get a journalctl log from about 15 minutes right around such a freeze, see the examples here:
http://0pointer.de/blog/projects/journalctl.html
journalctl --since=2016-03-17 12:00:00 --until="2016-03-17 12:15:00"

**Comment by AdamSadovsky** [comment]
Confirmed for live system. I left the system untouched after start until it fell asleep. After waking it up, panel is frozen and also yakuake crashed. Here is complete journalctl:
[https://gist.github.com/AdamSadovsky/c3e22358bfc8a74dde0c](https://gist.github.com/AdamSadovsky/c3e22358bfc8a74dde0c)

Because I don't have spare USB or DVD, I did started live ISO from HDD as described here:
[https://kaosx.us/phpBB3/viewtopic.php?f=4&t=1365](https://kaosx.us/phpBB3/viewtopic.php?f=4&t=1365).

**Comment by demmm** [comment]
Please point to what time the freeze happened.
Also, what is the graphics card?  Only shows integrated with a very strange resolution.
You mean you installed your latest KaOS this way?  Did not use a supported install from USB or DVD?

**Comment by AdamSadovsky** [comment]
I updated gist:
[https://gist.github.com/AdamSadovsky/c3e22358bfc8a74dde0c](https://gist.github.com/AdamSadovsky/c3e22358bfc8a74dde0c)
Computer went to sleep at : 19:23
I woke it up at : 19:28

I have standard resolution 1920x1080

This test was done under runing live ISO from DVD. But it was not clean start. Booting fail to emergency terminal after waiting 30 seconds for KaOS device. I mount it manually and continue booting. I was not able to burn it at 4x - k3b says that this speed is not supported by burner or DVD media. But test of this media is clean.

**Comment by AdamSadovsky** [comment]
I tried DVD in another computer (notebook) and there it boots without problem. And waking from sleep was OK on this notebook.
So I tried to copy ISO to USB flash drive and boot it. This time booting live USB on my PC was OK. But problem with panel after sleep persists. There was no difference If I boot live system with or without nvidia drivers and changes I made in bios did not help either (like graphical memory size, efi boot, some intel speed step something).
I believe that previos ISO was OK. But I will test it and also try other settings about graphics.

**Comment by AdamSadovsky** [comment]
I checked previos ISO 2016.01 and boot it from USB flash drive. It has no problem with waking up after sleep. But this time it is very slow - every read/write operation takes lots of time to finish. This I already experienced with my first boot of KaOS with this very version of ISO. Maybe some bad carma :) or something wrong with computer, but I run Kubuntu on them for a year without problem.

**Comment by demmm** [comment]
This all points to your graphics card.
See https://github.com/KaOSx/live-uefi/issues/8

Test with systemsettings > display > compositor > Rendering backend > set to XRender

**Comment by AdamSadovsky** [comment]
I already try it. Now I do it again with other settings and combinations. Still the same.

**Comment by AdamSadovsky** [comment]
Now I know what condition triggers panel to freez: I only need to turn monitor off and on. This is why disabling sleep doesn't help, because in this scenario I allways turn monitor off manually. But I don't know why this is happening.

**Comment by AdamSadovsky** [comment]
Maybe this bugreport?: https://bugreports.qt.io/browse/QTBUG-42985

**Comment by demmm** [comment]
Check with this ISO:
https://kaosx.us/phpBB3/viewtopic.php?f=18&t=1405#p7435
Qt 5.6 should fix a lot of these monitor connecting bugs

**Comment by AdamSadovsky** [comment]
This ISO is OK. No problem with monitor connection/disconnection. Does it also mean, that kde-next repository shall also contains this fix?

**Comment by demmm** [comment]
No, all is already in [build], will move to all users this Tuesday, when KDE announces Plasma 5.6.0
kde-next is currently empty
