### ISSUE TITLE
encfs: libencfs.so.6: undefined symbol ...

### ISSUE THREAD

**Issue by padhia** [KaOSx/main#27]
#### Submission type

  - [ X] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for
> encfs 1.8.1-5

#### Used repositories

> core, main, apps

#### Expected behaviour

> successfully mount encrypted volume

#### Actual behaviour

> encfs invocation fails with 
`encfs: symbol lookup error: /usr/lib/../lib/libencfs.so.6: undefined symbol: _ZN5boost7archive17xml_iarchive_implINS0_12xml_iarchiveEE4loadERSs`

#### Steps to reproduce the problem

> Try mounting any valid encfs volume from command-line.

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/5c6abb3df05385cb3b51428cf9d21a11

**Comment by demmm** [comment]
Please check if encfs in [build] fixes this issue, if so it will be moved right away:
```
sudo pacman -U http://kaosx.tk/repo/build/encfs-1.8.1-6-x86_64.pkg.tar.xz
```

**Comment by padhia** [comment]
That fixed it. Thanks!

**Comment by demmm** [comment]
New encfs moved to the [main] repo, closing.
