### ISSUE TITLE
Boost.Python error in task "bootldr"

### ISSUE THREAD

**Issue by alekzxd** [KaOSx/main#28]
Hello, I have two laptops, Sony Vaio with KaOS installed, and Dell N5110 where I tried to install KaOS, but an error ocurrs around 80% of progress (in Dell laptop). It say something like this:

Installation failed
Boost.Python error in task "bootldr"
<class 'subprocess.CalledProcessError'>
Command 'grub-install/dev/sda' returned non-zero exit status 1
Traceback:
File "/usr/lib/calamares/modules/bootldr/main.py", line 172, in run install_bootloader/boot_loader, fw_type)
File "/usr/lib/calamares/modules/bootldr/main.py", line 159, in install_bootloader check_target_env_call(["grub_install", install_path])
File "<string>", line 2, in <module>

I don't know what happen, some suggest?
I have used the same ISO that I used to install the Sony laptop: KaOS-2016.03-x86_64.iso

**Comment by demmm** [comment]
First of, always try to use the latest ISO, the one you are using is severely outdated, you will have to completely replace that install on first pacman -Syu.
Use latest, KaOS 2016.07:
http://kaosx.us/download

For installations issues, provide info as requested here:
http://kaosx.us/docs

But this report will be closed, nothing to with packages in the main repo, please open a bug report for the installer, see:
https://kaosx.us/bugs
