### ISSUE TITLE
xf86-video-vmware depends on outdated llvm

### ISSUE THREAD

**Issue by angiest** [KaOSx/main#29]
#### Submission type

  - [ x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> xf86-video-vmware 13.1.0-4

#### Used repositories

> default

#### Expected behaviour

> Display should come up on vmware driver

#### Actual behaviour

> Display doesn't come up, complains about libLLVM.  ldd on the driver shows a dependency on libLLVM.so.3.7, but 3.8 is what is currently available.

#### Steps to reproduce the problem

> On a vmware VM, install the vmware video driver and restart sddm.

#### System info link created by Octopi > Tools > SysInfo

> Can't get to a GUI to generate this.

**Comment by angiest** [comment]
I'm able to workaround this by creating a symlink from libLLVM.so.3.7 to libLLVM.so.

**Comment by demmm** [comment]
Thanks for reporting, rebuild vmware is up.  If possible install with pacman -U.  If it fixes the issue will be moved right away to all users:
```
sudo pacman -U http://kaosx.tk/repo/build/xf86-video-vmware-13.1.0-5-x86_64.pkg.tar.xz
```

**Comment by angiest** [comment]
Works. Thanks for the quick response!

**Comment by demmm** [comment]
xf86-video-vmware-13.1.0-5-x86_64.pkg.tar.xz moved, closing now.
