### ISSUE TITLE
Can't Connect Android Phone Via USB

### ISSUE THREAD

**Issue by opticyclic** [KaOSx/main#32]
#### Submission type

    Bug report

#### Package name & version you are having issues with or have a request for

I think other KDE distros package these:

    kio_mtp
    libmtp (already installed) 
    mtpfs

#### Used repositories

    Defaults

#### Expected behaviour

When I plug my android phone (Galaxy Nexus on Marshmallow) into my laptop with the USB cable I can browse the internal hard drive with Dolphin.

#### Actual behaviour

The phone is not recognised.

#### Steps to reproduce the problem

Install or load the live cd.
Plug an Android phone into a USB port.
Wait for Dolphin to open with your internal storage mounted.

**Comment by demmm** [comment]
kio_mtp is for old KDE 4 and not needed (or available) with plasma 5 and kio-extras.
Issue cannot be reproduced with multiple android devices tested.  In fact the Galaxy nexus was used here until a short while ago with no issues on USB/file sharing.
Make sure your device is setup to connect as file sharing, not connected as charging only.

**Comment by demmm** [comment]
No further response from submitter, closing.
