### ISSUE TITLE
Kmail is missing libgpgme-pthread.so.11

### ISSUE THREAD

**Issue by bison-paolo** [KaOSx/main#33]
#### Submission type

  - [X] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> gpgme 1.8.0-2

#### Used repositories

> main

#### Expected behaviour

> The soft link libgpgme-pthread.so.11 to libgpgme.so.11.17.0, present in /usr/lib/

#### Actual behaviour

> The soft link libgpgme-pthread.so.11 to libgpgme.so.11.17.0 is missing in the directory /usr/lib/

#### Steps to reproduce the problem

> Running kmail

#### System info link created by Octopi > Tools > SysInfo

> Kmail returns the following message: "kmail: error while loading shared libraries: libgpgme-pthread.so.11: cannot open shared object file: No such file or directory"

**Comment by demmm** [comment]
Issue is already fixed in [build] (a few hours ago), just install gpgmepp maually for now:
```
sudo pacman -U http://kaosx.tk/repo/build/gpgmepp-16.08.3-2-x86_64.pkg.tar.xz
```
Once moved to all users, then this issue will be closed.

**Comment by bison-paolo** [comment]
Thanks a lot!

**Comment by demmm** [comment]
gpgmepp-16.08.3-2 is now in the [apps] repo, closing.
