### ISSUE TITLE
hugin_executor

### ISSUE THREAD

**Issue by bison-paolo** [KaOSx/main#34]
#### Submission type

  - [ ] Bug report
  - [X] Feature Request

#### Package name & version you are having issues with or have a request for

> hugin-tools 2016.2.0-1

#### Used repositories

> main

#### Description

> Could you please compile hugin against the wxWidgets? Because the the interface of the executable  hugin_executor is based on this library. Without this executable is not possible to stitch panoramas in digikam.
> Thanks!

**Comment by demmm** [comment]
Sorry, won't be implemented. Default in KaOS will stay GTK free, wxWidgets will certainly not be added as default.
It is not hard though to build it yourself and add features you like:
https://kaosx.us/docs/package/
Current used hugin PKGBUILD:
https://github.com/KaOSx/main/blob/master/hugin-tools/PKGBUILD
remove the sed line on line 25 and add wxgtk2.9 to the depends.

You are free to add such a (renamed) hugin package to KCP.
