### ISSUE TITLE
NM-openvpn connectivity issue 

### ISSUE THREAD

**Issue by Seeder101** [KaOSx/main#37]
#### Submission type

  - [*] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> networkmanager-openvpn

#### Used repositories

> main

#### Expected behaviour

> connectivity issue with VPN in networkmanager applet 

#### Actual behaviour
> the connection doesn't establish at all it just hangs

#### Steps to reproduce the problem

> I did solve the issue by doing the following 
1- nano /usr/lib/sysusers.d/nm-openvpn.conf
2- adding the following in the conf file :: 
u nm-openvpn - -
g nm-openvpn - -
save the file after
3- do sudo systemd-sysusers /usr/lib/sysusers.d/nm-openvpn.conf 
and that's it after I did these steps the openvpn setup worked 

#### System info link created by Octopi > Tools > SysInfo

> https://gist.github.com/082d5f992cf419308724d8005f6daa49

Thank you very much <3

**Comment by demmm** [comment]
Packaging can be altered here, but did you check upstream why this is not added if such a file is needed?

**Comment by abucodonosor** [comment]
@demmm 

I think the methode does not matter systemd  way or some .install file..  it does need the user / group.

This is hardcoded in the source ..

shared/nm-service-defines.h:#define NM_OPENVPN_GROUP  "nm-openvpn"


I do that with an install file in FW.

**Comment by demmm** [comment]
So far, that is how it was done in KaOS too, user was added in a .install file:
https://github.com/KaOSx/main/blob/master/networkmanager-openvpn/networkmanager-openvpn.install
(line 6 was just added now).

**Comment by Seeder101** [comment]
so basically the .install will add the user/group id because of the 6th line you've added,right?

**Comment by demmm** [comment]
No, the users were always created, line 6 is just added according your suggestions for the added .conf file in the initial post.  That line has nothing to do with user creation.

**Comment by demmm** [comment]
No response from OP about the question asked, time to close.

**Comment by Seeder101** [comment]
Hi demmm, after adding that line 6 things should be working so eventually it's solved so closing the issue is fine. Thank you
