### ISSUE TITLE
frozen screen

### ISSUE THREAD

**Issue by ki00** [KaOSx/main#38]
#### Submission type

when I let the laptop on, when I return it is freezed (the music continues playing)

#### Package name & version you are having issues with or have a request for

> …Kaos201706

#### Used repositories

> …update

#### Expected behaviour

> …do not freeze

#### Actual behaviour

> …it freezes, need to restart the pc

#### Steps to reproduce the problem

> …use the computer, let it on and come back and it is freezed

#### System info link created by Octopi > Tools > SysInfo
journalctl log
https://gist.github.com/ki00/04c195777735aa831d75df7925f1cc92

another command:
[user@user ~]$ sudo journalctl -b -p err 
Contraseña:  
-- Logs begin at Mon 2017-06-19 09:22:25 -05, end at Mon 2017-06-19 11:49:37 - 
jun 19 11:45:29 user systemd-udevd[208]: specified group 'plugdev' unknown 
jun 19 11:45:37 user kernel: usb 3-1.3: device descriptor read/64, error -110 
jun 19 11:47:07 user ntpd[439]: bind(23) AF_INET6 fe80::d5e7:ebca:8203:e450%3# 
jun 19 11:47:07 user ntpd[439]: unable to create socket on wlp2s0 (4) for fe80 
lines 1-5/5 (END)

**Comment by demmm** [comment]
Is this issue still present?
