### ISSUE TITLE
Kwin issue with Nvidia non free

### ISSUE THREAD

**Issue by pasnox** [KaOSx/main#40]
#### Submission type

  - [x ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> Kwin
> Libepoxy

#### Used repositories

> Default

#### Expected behaviour

> Kwin opengl support working

#### Actual behaviour

> Only xrender works

#### Steps to reproduce the problem

> Install Nvidia non free and try to enable desktop effects

The issue is caused by a change in libepoxy, see https://bugs.kde.org/show_bug.cgi?id=392863
After having reverted the change and rebuilding the package, kwin works again correctly.

**Comment by demmm** [comment]
Could you post the output of `inxi -G` (trying to see if it only effects legacy nvidia)?

**Comment by pasnox** [comment]
Here is it:

Graphics:  Card-1: NVIDIA GK107M [GeForce GT 750M Mac Edition] driver: nvidia v: 390.48 
           Display Server: x11 (X.Org 1.19.6) driver: nvidia resolution: 1920x1080~60Hz, 2880x1800~60Hz 
           OpenGL: renderer: GeForce GT 750M/PCIe/SSE2 v: 4.6.0 NVIDIA 390.48

**Comment by demmm** [comment]
Libepoxy is now build with one commit reverted, please test if that fixes your issues:
```
sudo pacman -U http://kaosx.tk/repo/build/libepoxy-1.5.1-2-x86_64.pkg.tar.xz
```

**Comment by pasnox** [comment]
That fix it, thanks.

On dimanche 6 mai 2018 19:59:21 CEST demmm wrote:
> Libepoxy is now build with one commit reverted, please test if that fixes
> your issues: ```
> sudo pacman -U http://kaosx.tk/repo/build/libepoxy-1.5.1-2-x86_64.pkg.tar.xz
> ```


-- 
Filipe Azevedo

**Comment by demmm** [comment]
Libepoxy 1.5.1-2 moved to the [main] repo, closing.
