### ISSUE TITLE
Shiboken is not a 2.0 but 1.2.4

### ISSUE THREAD

**Issue by luzpaz** [KaOSx/main#45]
please fix the [shiboken package](https://github.com/KaOSx/main/blob/master/shiboken/PKGBUILD) per this badge:

CC @demmm 

[![Packaging status](https://repology.org/badge/vertical-allrepos/shiboken.svg)](https://repology.org/metapackage/shiboken/versions)

**Comment by demmm** [comment]
Make sure to check the correct used shiboken, since KaOS uses just one shiboken, this is:
http://code.qt.io/cgit/pyside/shiboken.git/tree/README.md
See the PKGBUILD:
https://github.com/KaOSx/main/blob/master/shiboken/PKGBUILD
