### ISSUE TITLE
qt5-sql, qt5-sql-devel and sql plugins packages are missing

### ISSUE THREAD

**Issue by SzykCech4** [KaOSx/main#48]
#### Submission type

  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> 5.13.1 or newer

#### Used repositories

> ?

#### Expected behaviour

> Easy to install qt5-sql, qt5-sql-devel and sql plugins packages

#### Actual behaviour

> Qt5 sql packages can not be installed.

#### Steps to reproduce the problem

>  pacman -Ss qt5-sql

#### System info link created by Octopi > Tools > SysInfo

> [octopi-sysinfo-1928786029.log](https://github.com/KaOSx/main/files/3775104/octopi-sysinfo-1928786029.log)

**Comment by demmm** [comment]
If you would have checked what Qt releases:
http://download.qt-project.org/official_releases/qt/5.13/5.13.1/submodules/then you would know there is no such package, just whatever distro you used before made that up.  All sql is part of qt5-base `pacman -Ql qt5-base | grep sql`

**Comment by demmm** [comment]
Also, this is the bug tracker, not help channel or requests, please don't abuse the tracker, use the forum for requests and help.  And read the website about what KaOS is and how it packages (splitting of packages kept to a minimum for example).

**Comment by SzykCech4** [comment]
This post was clearly marked as: "Feature Request". If this is not right place to put "Feature Request"s then sorry. But I am not aware of that. I also read all pages from KaOS web page.
