### ISSUE TITLE
Widevine not working at all on Google Chrome, Vivaldi and Falkon

### ISSUE THREAD

**Issue by EQLucky** [KaOSx/main#50]
#### Submission type

  - [ X ] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> QTWebEngine v. 5.14.1-1

#### Used repositories

> Build, Core, Main, Apps

#### Expected behaviour

> Widevine dependant sites aren't working on Google Chrome.

#### Actual behaviour

> Widevine isn't working at all. It shows version 0.0.0.0 and won't update. Tried to delete pacman cache, uninstalled both apps (browser and qtwebengine) and reinstalled. Didn't work.

#### Steps to reproduce the problem

> Launch Netflix on Google Chrome, log in and try to stream any content. It shows error M7701-1003.

#### System info link created by Octopi > Tools > SysInfo

> 
[octopi-sysinfo-553041640.log](https://github.com/KaOSx/main/files/4366333/octopi-sysinfo-553041640.log)

**Comment by EQLucky** [comment]
I wanted to point this is an issue that happened to a Kaos Telegram group member, and the sysinfo added is from my system, but the issue is the same.

**Comment by demmm** [comment]
Not clear what package this is about, report states QtWebengine, but then talks about Widevine, for which there are two versions in the repositories. Google chrome needs widevine, Falkon needs qtwebengine-widevine, latter won't work on Chrome, so please clarify.  And Vivaldi is not part of KaOS.

**Comment by EQLucky** [comment]
Ok, I didn't know that.
It isn't working on Chrome, so the package in conflct is widevine. Just tried on Falkon (installed qtwebengine-widevine and removed widevine) and it works there.

**Comment by demmm** [comment]
So not a [main] issue (QtWwebengine), but apps.....
Any timeline when the issue started for widevine in Chrome? Not much to do with packaging, since both widevine and chrome are closed source and nothing is build, it is just shipping their files.

**Comment by demmm** [comment]
Looks to be known upstream:
https://bugs.chromium.org/p/chromium/issues/detail?id=1064949&q=hdcp%20OS%3DLinux&can=2

**Comment by demmm** [comment]
Issue is fixed since widevine 84.0.4143.2
