### ISSUE TITLE
Please include kio-fuse by default

### ISSUE THREAD

**Issue by Pointedstick** [KaOSx/main#53]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

#### Package name & version you are having issues with or have a request for

> kio-fuse

#### The request

kio-fuse is the KDE equivalent of GNOME's GVfs, which like the GNOME version substantially improves the experience of interacting with remote files using non-native software by exposing the remote file and its parent folder to the app using a FUSE interface.

This package is available in the repos, but not installed automatically. I would like to request that it be installed by default, to improve the out-of-the-box experience for KDE Plasma users and bring the Plasma session to feature parity with the user experience for users of the GNOME desktop and its forks (which get GVfs pre-installed by default).

**Comment by demmm** [comment]
Thanks for the report, I just received the KDE packagers mail too, and was looking where I will add.  Meta package is not used much here, I will make it a depend of either Dolphin or Plasma-desktop, so all users will get it, regardless.

**Comment by demmm** [comment]
Implemented:
https://github.com/KaOSx/apps/commit/1239fa0f9528fac39df763b21c4a3c887ca121c3

**Comment by Pointedstick** [comment]
Thank you very much!
