### ISSUE TITLE
dolphin/samba asks for user/pw again and again

### ISSUE THREAD

**Issue by AlexLevkovich** [KaOSx/main#54]
#### Submission type

  - [* ] Bug report
  - [* ] Feature Request

#### Package name & version you are having issues with or have a request for

> samba

#### Used repositories

> main

#### Expected behaviour

> dolphin should show the contents of remote server. It works with samba 4.13.

#### Actual behaviour

> dolphin asks for user/pw again and again. smb.conf is default. 

#### Steps to reproduce the problem

> just use dolphin to connect to some remote windows pc with some free accessible share using smb://pcname

#### System info link created by Octopi > Tools > SysInfo

> ----------------------------------------------------------------------------------------------------------
cat /etc/KaOS-release
----------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------
inxi -Fxz
----------------------------------------------------------------------------------------------------------

System:    Kernel: 5.14.11-1 x86_64 bits: 64 compiler: gcc v: 10.3.0 Desktop: KDE Plasma 5.23.0 
           Distro: KaOS 2021 
Machine:   Type: Virtualbox System: innotek product: VirtualBox v: 1.2 serial: <filter> 
           Mobo: Oracle model: VirtualBox v: 1.2 serial: <filter> BIOS: innotek v: VirtualBox 
           date: 12/01/2006 
Battery:   ID-1: BAT0 charge: 50.0 Wh (100.0%) condition: 50.0/50.0 Wh (100.0%) volts: 10.0 
           min: 10.0 model: innotek 1 status: Full 
CPU:       Info: Quad Core model: Intel Core i5-7300HQ bits: 64 type: MCP arch: Kaby Lake rev: 9 
           cache: L2: 6 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 bogomips: 19967 
           Speed: 2496 MHz min/max: N/A Core speeds (MHz): 1: 2496 2: 2496 3: 2496 4: 2496 
Graphics:  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.18.1.0 bus-ID: 00:02.0 
           Display: x11 server: X.Org 1.20.13 driver: loaded: vmware unloaded: modesetting,vesa 
           resolution: 1808x901~60Hz 
           OpenGL: renderer: SVGA3D; build: RELEASE; LLVM; v: 2.1 Mesa 21.2.3 direct render: Yes 
Audio:     Device-1: Intel 82801AA AC97 Audio vendor: Dell driver: snd_intel8x0 v: kernel 
           bus-ID: 00:05.0 
           Sound Server-1: ALSA v: k5.14.11-1 running: yes 
           Sound Server-2: JACK v: 1.9.19 running: no 
           Sound Server-3: PulseAudio v: 15.0 running: yes 
           Sound Server-4: PipeWire v: 0.3.38 running: no 
Network:   Device-1: Intel 82540EM Gigabit Ethernet driver: e1000 v: kernel port: d010 
           bus-ID: 00:03.0 
           IF: enp0s3 state: up speed: 1000 Mbps duplex: full mac: <filter> 
           Device-2: Intel 82371AB/EB/MB PIIX4 ACPI type: network bridge driver: piix4_smbus 
           v: N/A port: d200 bus-ID: 00:07.0 
Drives:    Local Storage: total: 0 KiB used: 0 KiB 
Partition: ID-1: / size: 2.88 GiB used: 62.6 MiB (2.1%) fs: aufs source: ERR-102 
Swap:      Alert: No swap data was found. 
Sensors:   Message: No sensor data found. Is lm-sensors configured? 
Info:      Processes: 159 Uptime: 1m Memory: 3.84 GiB used: 899.8 MiB (22.9%) Init: systemd 
           runlevel: 5 Compilers: gcc: 10.3.0 Packages: 942 Client: Unknown Client: octopi 
           inxi: 3.3.06 

----------------------------------------------------------------------------------------------------------
journalctl -b -p err
----------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------
cat /etc/pacman.conf
----------------------------------------------------------------------------------------------------------

#
# /etc/pacman.conf
#
# See the pacman.conf(5) manpage for option and repository directives

#
# GENERAL OPTIONS
#
[options]
# The following paths are commented out with their default values listed.
# If you wish to use different paths, uncomment and update the paths.
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
HoldPkg     = pacman glibc pacman-helpme
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#XferCommand = /usr/bin/curl %u > %o
#CleanMethod = KeepInstalled
#UseDelta    = 0.7
Architecture = auto

# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
IgnorePkg   = 
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

# Misc options (all disabled by default)
#NoPassiveFtp
#UseSyslog
Color
#TotalDownload
CheckSpace
VerbosePkgLists
ILoveCandy

# By default, pacman accepts packages signed by keys that its local keyring
# trusts (see pacman-key and its man page), as well as unsigned packages.
SigLevel = Never
LocalFileSigLevel = Never
#RemoteFileSigLevel = Required

#
# REPOSITORIES
#   - can be defined here or included from another file
#   - pacman will search repositories in the order defined here
#   - local/custom mirrors can be added here or in separate files
#   - repositories listed first will take precedence when packages
#     have identical names, regardless of version number
#   - URLs will have $repo replaced by the name of the current repo
#
# Repository entries are of the format:
#       [repo-name]
#       Server = ServerName
#       Include = IncludePath
#
# The header [repo-name] is crucial - it must be present and
# uncommented to enable the repo.
#

[core]
Include = /etc/pacman.d/mirrorlist

[main]
Include = /etc/pacman.d/mirrorlist

[apps]
Include = /etc/pacman.d/mirrorlist

# An example of a custom package repository.  See the pacman manpage for
# tips on creating your own repositories.
#[custom]
#Server = file:///home/custompkgs

----------------------------------------------------------------------------------------------------------
pacman -Qm
----------------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------------
cat /var/log/pacman.log
----------------------------------------------------------------------------------------------------------

[2021-10-11T13:54:13+0000] [PACMAN] Running 'pacman -r work-x86_64/root-image -Syu --config pacman.conf -v'
[2021-10-11T13:54:13+0000] [PACMAN] synchronizing package lists
[2021-10-11T13:54:13+0000] [PACMAN] starting full system upgrade
[2021-10-11T13:54:15+0000] [ALPM] transaction started
[2021-10-11T13:54:15+0000] [ALPM] upgraded calamares (3.2.44.3-5 -> 3.2.44.3-6)
[2021-10-11T13:54:16+0000] [ALPM] upgraded calamares-debug (3.2.44.3-5 -> 3.2.44.3-6)
[2021-10-11T13:54:16+0000] [ALPM] transaction completed
[2021-10-11T13:54:16+0000] [ALPM] running 'update-desktop-database.hook'...

----------------------------------------------------------------------------------------------------------
cat /var/log/installation.log
----------------------------------------------------------------------------------------------------------

**Comment by demmm** [comment]
It seems this is not an installed system, but live, virtualbox issue? Have you followed https://kaosx.us/docs/samba/ to setup samba?

**Comment by AlexLevkovich** [comment]
I have the same issue on all systems (on real hardware) where samba > 4.13. I suppose it is the reason why Ubuntu does not increase the version of samba.
I registered the same bug in many places. I just wondering if someone is ready to fix it. gvfs has the same issue. And virtual system  is not a reason not to fix this.

**Comment by demmm** [comment]
No response to asked question regarding proper samba setup, waiting over a year is long enough, closing.
