### ISSUE TITLE
Possible dbus related issue with Pipewire

### ISSUE THREAD

**Issue by fjmorazan** [KaOSx/main#55]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> pipewire 0.3.40-2

#### Used repositories

> build repo

#### Expected behaviour

> Pipewire's audio session to work

#### Actual behaviour

> No audio with pipewire service enabled

#### Steps to reproduce the problem

> systemctl --user enable --now pipewire-pulse.{service,socket}
> Logout and log back in

#### System info link created by Octopi > Tools > SysInfo

> [Sysinfo](https://paste.opensuse.org/13388842)

**Comment by demmm** [comment]
With the last 2 commits for pipewire, it is shifted to system services, not user:
https://github.com/KaOSx/main/commits/master/pipewire
That said, I have not been able yet either to get it to work, please also try with `sysetmct -enable pipewire.....`
Check the working of wireplumber too.

**Comment by fjmorazan** [comment]
Hi demm, sorry for the late response

I tried enabling pipewire as system services without [luck](https://paste.opensuse.org/0914e22d), then I tried to fiddle with wireplumber as user service using the [docs](https://pipewire.pages.freedesktop.org/wireplumber/running-wireplumber-daemon.html) of the project. I think I'll be using the default audio solution for the time being

**Comment by demmm** [comment]
Issue will stay open, since I am working on getting this to be implemented (and should become default in the next few months).

**Comment by fjmorazan** [comment]
Hi! Just an update about pipewire. It seems all I need to do now is just to issue the command `systemctl enable --user --now wireplumber` to use it as default audio server, without needing to enable the pipewire and pipewire-pulse service

'''bash
$ systemctl status --user 
● t440p-ks
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Sat 2022-01-29 11:36:45 CST; 2min 53s ago
   CGroup: /user.slice/user-20378.slice/user@20378.service
           ├─init.scope
           │ ├─1394 /usr/lib/systemd/systemd --user
           │ └─1395 "(sd-pam)"
           └─session.slice
             ├─pipewire.service
             │ └─3315 /usr/bin/pipewire
             └─wireplumber.service
               └─3316 /usr/bin/wireplumber
'''

**Comment by demmm** [comment]
But, how to check now if sound actually goes over pipewire?

**Comment by fjmorazan** [comment]
I was wrong, it seems I need to enable pipewire-pulse to make pipewire the audio server

```
$ pactl info | grep "Server Name"
Server Name: pulseaudio
┌─francisco@t440p-ks [~]
└──>$ systemctl enable --now --user wireplwireplumber.service 
Created symlink /home/francisco/.config/systemd/user/pipewire-session-manager.service -> /usr/lib/systemd/user/wireplumber.service.
Created symlink /home/francisco/.config/systemd/user/pipewire.service.wants/wireplumber.service -> /usr/lib/systemd/user/wireplumber.service.
┌─francisco@t440p-ks [~]
└──>$ systemctl enable --user --now pipewire-pulse.{service,socket}
Created symlink /home/francisco/.config/systemd/user/default.target.wants/pipewire-pulse.service -> /usr/lib/systemd/user/pipewire-pulse.service.
Created symlink /home/francisco/.config/systemd/user/sockets.target.wants/pipewire-pulse.socket -> /usr/lib/systemd/user/pipewire-pulse.socket.
┌─francisco@t440p-ks [~]
└──>$ pactl info | grep "Server Name"
Server Name: PulseAudio (on PipeWire 0.3.44)
```

Now the only problem that remains is that I have to restart wireplumber whenever I boot the system to be able to use the audio devices

**Comment by demmm** [comment]
Thanks for checking into this.  Works here too on a per user basis (and started during a session).
If pipewire just works, then it should become default and needs to be enabled/run system wide, will look into this.

**Comment by demmm** [comment]
Pipewire now `just works` and is default for KaOS, closing.
