### ISSUE TITLE
bluez 5.64 fix servcie not starting when missing the state

### ISSUE THREAD

**Issue by mendez42** [KaOSx/main#56]
#### Submission type

  - [x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> bluez 5.64-1

#### Used repositories

> main

#### Expected behaviour

> service starting

#### Actual behaviour

> servcie not starting

#### Steps to reproduce the problem

> try start BT

#### System info link created by Octopi > Tools > SysInfo

> …

Needs fix like this:

https://github.com/archlinux/svntogit-packages/commit/ec96253dff1d9892879cd4682840817fff817236

**Comment by demmm** [comment]
Better not blindly copy what others do, upstream acknowledges that the change in 5.64 is not correct, and has removed the need for that directory:
https://github.com/bluez/bluez/commit/0905a06410d4a5189f0be81e25eb3c3e8a2199c5

Rebuild will be done with some patches from upstream.
