### ISSUE TITLE
PHP Upgrade to Version 8.2

### ISSUE THREAD

**Issue by Ndashka-Dev** [KaOSx/main#59]
#### Submission type

  - [ ] Bug report
  - [x] Feature Request

#### Package name & version you are having issues with or have a request for

> php-8.1.17-2 and php-apache-8.1.17-2

#### Used repositories

> main

#### Expected behaviour

> PHP 8.2 has been released, so, perhaps, there should be an option to install it? Could PHP 8.2 be included into the build repositories, or be php-next like linux-next?

**Comment by demmm** [comment]
PHP always lags behind the latest upstream major new version, so all servers can catch up & prepare for a new major release. See:
https://kaosx.us/about/based/ section with
```
Packages that are still maintained in an older version and were many in KDE depend on, will not move to the latest, until most upstream projects have caught up with the newer version
```
PHP usually moved to next major around x.x.5/6 so it won't be much longer.
