### ISSUE TITLE
error in the connection network

### ISSUE THREAD

**Issue by mcder3** [KaOSx/main#6]
Yesterday install the latest version of KaOS KF5, after upgrading networkmanager disconnects every moment.

The only way I've managed to connect is enabled dhcpcd service.

Screenshot:

http://i.imgur.com/KoJgrha.png

Log Files:

https://drive.google.com/folderview?id=0B7tTd_BxrUN3b3NXM0FLVXpYYU0&usp=sharing

**Comment by demmm** [comment]
Closing.  Issue resolved for original poster, no further logs or info from subsequent poster.
