### ISSUE TITLE
No mouse cursor/touchpad cursor - Live Media

### ISSUE THREAD

**Issue by GeneMCO61** [KaOSx/main#62]
#### Submission type

  - [ x] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> KaOS-2023.11-x86_64.iso

#### Used repositories

> https://mirror.math.princeton.edu/pub/kaoslinux/

#### Expected behaviour

> Mouse cursor/function (touchpad)

#### Actual behaviour

>No mouse cursor/touchpad cursor 

#### Steps to reproduce the problem
>HP Zbook 14 G10 A - live media USB via YUMI install for trial/demo use. 
System boots beautifully , but no mouse cursor/mouse touchpad support.
Keyboard support only.

#### System info link created by Octopi > Tools > SysInfo

> …?

**Comment by demmm** [comment]
For a usable bug report, SysInfo is needed:
https://kaosx.us/docs
https://kaosx.us/docs/#sysinfo-tool-in-octopi
And not clear if you used an unsupported way to create the live media, only supported are:
https://kaosx.us/docs/usb_flash/

**Comment by demmm** [comment]
No further response from submitter, closing.
