### ISSUE TITLE
Octopi and other no in systemtray

### ISSUE THREAD

**Issue by Astate** [KaOSx/main#64]
#### Submission type

  - [X] Bug report
  - [ ] Feature Request

#### Package name & version you are having issues with or have a request for

> 2024.01 ISO

#### Used repositories

> iso from sourceforge

#### Expected behaviour

have octopi-notifier in systemtray

#### Actual behaviour

no icon of octopi in systemtray but the process are running
$ ps -aux | grep octopi-notifier                                                 
user    1105  0.0  1.4 1069776 115800 ?      Ssl  14:00   0:00 /usr/bin/octopi-notifier
user    2223  0.0  0.0   9088  2388 pts/0    S+   14:37   0:00 grep --color=tty -d skip octopi-notifier

journalctl -b --no-pager | grep -i sni
fév 14 14:01:20 laptopkaos octopi-notifier[1105]: kf.statusnotifieritem: env says KDE is running but SNI unavailable -- check KDE_FULL_SESSION and XDG_CURRENT_DESKTOP

#### Steps to reproduce the problem

- I downloaded the ISO a second time and made the checksum
- I completely reinstall 3 times KaOs. it's always same.
In first test , i install Kaos, remove some things,  do update, add software and no Octopi-Notifier
In the second test , i install Kaos minimal, in first boot, i do update, and after I started Octopi-Notifier
In last test, i install Kaos minimal, in first boot, before doing anything, I started Octopi-Notifier

#### System info link created by Octopi > Tools > SysInfo

https://paste.ee/p/gEsEd

**Comment by demmm** [comment]
Not an issue for main, but will leave it here for now, this is clearly about applications, so needs to be under Apps:
https://github.com/KaOSx/apps/issues

Does the octopi-notifier show in Live mode?  Does it show on first boot into new install?
If so, then what theme is in use after the update and the notifier no longer showing?  Is it a matter of no icon for the notifier, so just an empty space in the panel?

**Comment by Astate** [comment]
After the installation I closed Crosedo without modifying anything and I tested the notification problem.
This is not only a problem with Octopi, I had the same problem with the Flatpak client NextCloud application.
it's not only probleme of icons, i dont have empty space.
I will test the Live ISO

**Comment by demmm** [comment]
Asking one more time, did you have the issue in live mode?  Did you have the issue on booting into the new install?  So before updating/installing anything.  Flatpak is not part of a default install.

**Comment by Astate** [comment]
Same proplem on live iso -> https://i.imgur.com/BPk34xc.png

**Comment by Astate** [comment]
Asking one more time, did you have the issue in live mode? **yes**  https://i.imgur.com/BPk34xc.png
Did you have the issue on booting into the new install? So before updating/installing anything. **Yes** 
Flatpak is not part of a default install. it's because i wanted to tell you that it is not only Octopi who is in a problem

**Comment by demmm** [comment]
What happens if you don't use the the autostart .desktop file, but start the notifier manually?
```
killall octopi-notifier
```
```
/usb/bin/octopi-notifier
```

**Comment by Astate** [comment]
it's work when i start it manualy

**Comment by demmm** [comment]
One more `killall octopi-notifier`, and now start it from the menu.

**Comment by Astate** [comment]
it's also work.

**Comment by demmm** [comment]
OK, so the bug is in either autostart or the .desktop file set in autostart

**Comment by Astate** [comment]
It also explains the problem of NextCloud-Client I also added in "Automatic start" in Config Panel

**Comment by demmm** [comment]
I can replicate with a new entry in autostart (used stacer), it runs on reboot, but no systemtray entry (it does have an empty space, but not clickable), so it is an autostart issue.
I'll have to check upstream bug reports for this (or you can help), this most probably is not a packaging issue but rather an upstream bug.  KaOS can only correct packaging issues for bugs, not correct bugs in code.

**Comment by Astate** [comment]
thank you for your work !

**Comment by Astate** [comment]
we probably dont want '\x2d' in file name here. ASCII 2d seems to be a simple hyphen (-).
 
```
❯ ls  /run/user/1000/systemd/generator.late
'app-at\x2dspi\x2ddbus\x2dbus@autostart.service'   
'app-pulseaudio@autostart.service'
'app-kaccess@autostart.service'                    
'app-xdg\x2duser\x2ddirs@autostart.service'
'app-octopi\x2dnotifier@autostart.service'        
'app-xdg\x2duser\x2ddirs\x2dupdate@autostart.service'
'app-org.kde.kdeconnect.daemon@autostart.service'   
xdg-desktop-autostart.target.wants/
'app-org.kde.kgpg@autostart.service'

```

```
❯ locale 
LANG=fr_CA.UTF-8
LC_CTYPE="fr_CA.UTF-8"
LC_NUMERIC=fr_CA.UTF-8
LC_TIME=fr_CA.UTF-8
LC_COLLATE="fr_CA.UTF-8"
LC_MONETARY=fr_CA.UTF-8
LC_MESSAGES="fr_CA.UTF-8"
LC_PAPER=fr_CA.UTF-8
LC_NAME=fr_CA.UTF-8
LC_ADDRESS=fr_CA.UTF-8
LC_TELEPHONE=fr_CA.UTF-8
LC_MEASUREMENT=fr_CA.UTF-8
LC_IDENTIFICATION=fr_CA.UTF-8
LC_ALL=
```

**Comment by Astate** [comment]
The last update solve the problem. 

the list of package i have updated : https://pastebin.com/Pspf8yrx

**Comment by demmm** [comment]
Looks like it is /was kdeconnect-kde blocking any sni during startup, removing kdeconnect-kde fixes autostart apps.
Removing was needed for the RC2 currently in stable, testing the final Megarelease here now with kdeconnect-kde 24.02.0 has the fix.
Issue will be closed once 24.02 is released next week.

**Comment by NoSavvy** [comment]
Could this be only on older/slower machines. I have and an older PC and cannot get the problem to arise, no matter how many times I reboot or whatever theme I use. Two separate installations. It fails on both my fast Intel PCs.
Just a thought.

**Comment by demmm** [comment]
Please check again after Wednesday.  Then Megarelease final will become available to all users.  Here on early testing of that release, issue is gone.

**Comment by Astate** [comment]
Yes issue is gone !
