### ISSUE TITLE
Noto font doesn't include all languages

### ISSUE THREAD

**Issue by na5810** [KaOSx/main#65]
#### Submission type

  - [x] Bug report
  - [x] Feature Request

#### Package name & version you are having issues with or have a request for

> noto-fonts

#### Used repositories

> main

#### Expected behaviour

> Date should show up in selected language.

#### Actual behaviour

> Only shows tofu.

#### Steps to reproduce the problem

> Choose locale.

#### System info link created by Octopi > Tools > SysInfo

> [octopi-sysinfo-3809377722.log](https://github.com/KaOSx/main/files/14814471/octopi-sysinfo-3809377722.log)

Thank you!

**Comment by demmm** [comment]
Not clear what is missing.  Since nothing is compiled, only packaged what upstream provides, it is possible what you are looking for is not included:
https://github.com/notofonts/notofonts.github.io/tree/main/fonts

**Comment by na5810** [comment]
Oh I see, I guess they're separate font files for different scripts - for some reason I thought they could be combined. Thanks!
