### ISSUE TITLE
Cython needs a rebuild

### ISSUE THREAD

**Issue by felipeacsi** [KaOSx/main#8]
Hello demm.

Since the move to python 3.4 it is necessary to rebuild this package. I tried to install both versions on my machine using the PKGBUILD from here but I got an error with `cythonize`.

The installation through the repositories goes "well" but  I got an error too:

    $ cython3 --help
    bash: /usr/bin/cython3: /usr/bin/python33: intérprete erróneo: No existe el fichero o el directorio

**Comment by demmm** [comment]
It was rebuild in the python 3.4 move, and has been rebuild/updated several more times after that.
https://github.com/KaOSx/main/commits/master/python-cython/PKGBUILD
post the output of:
pacman -Qi python3-cython
pacman -Qm

**Comment by felipeacsi** [comment]
Yeah... you are right. Here are the outputs:

> ~ $ pacman -Qi python3-cython
> Nombre            : python3-cython
> Versión           : 0.21.2-1
> Descripción       : C-Extensions for Python 3
> Arquitectura      : x86_64
> URL               : http://www.cython.org
> Licencias         : APACHE
> Grupos            : Nada
> Provee            : Nada
> Depende de        : python3
> Dep. opcionales   : Nada
> Requerido por     : Nada
> Opcional Para   : Nada
> En conflicto con    : Nada
> Reemplaza a         : Nada
> Tamaño instalado : 8909,00 KiB
> Empaquetador      : Anke Boersma <demm@kaosx.us>
> Fecha de compilación : sáb 27 dic 2014 18:25:20 CLST
> Fecha de instalación : mar 20 ene 2015 10:44:54 CLST
> Motivo de la instalación: Instalado explícitamente
> Script de instalación: No
> Validado Por   : Suma SHA256

~ $ pacman -Qm
> create-resources 0.1.3-3
> emacs 24.4-1
> libgcj 4.9.2.10-1
> libotf 0.9.13-1
> m17n-db 1.6.4-2
> m17n-lib 1.6.4-2
> pdftk 2.02.2-1
> python2-scipy 0.15.0-1
> python3-jedi 0.8.1-1
> python3-py 1.4.26-1
> python3-pytest 2.6.4-1
> python3-sexpdata 0.0.3-1
> python3-stevedore 0.15-1
> python3-tox 1.8.1-1
> python3-virtualenv 12.0.5-1
> python3-virtualenv-clone 0.2.4-1
> python3-virtualenvwrapper 4.3.2-1
> recoll 1.20.1-1
> speedcrunch 0.11-1
> spun 0.4-3

**Comment by KdeOs** [comment]
See what owns your file.
Pacman -Qo /usr/bin/cyton33

**Comment by felipeacsi** [comment]
I think is right

> ~ $ pacman -Qo /usr/bin/cython3
> /usr/bin/cython3 es propiedad de python3-cython 0.21.2-1

**Comment by demmm** [comment]
Not cython3, cython33

**Comment by felipeacsi** [comment]
> ~ $ pacman -Qo /usr/bin/cython33
> error: no se pudo leer el archivo '/usr/bin/cython33': No existe el fichero o el directorio

**Comment by demmm** [comment]
Issue found, the cython3 bin has the wrong shebang:

#!/usr/bin/python33
# EASY-INSTALL-ENTRY-SCRIPT: 'Cython==0.21.2','console_scripts','cython'
__requires__ = 'Cython==0.21.2'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('Cython==0.21.2', 'console_scripts', 'cython')()
    )

Fixed in python3-cython-0.21.2-2
http://kaosx.us/repo/build/python3-cython-0.21.2-2-x86_64.pkg.tar.xz

Issue will be closed when packages move to [main]

**Comment by felipeacsi** [comment]
Great! Thank you.

**Comment by demmm** [comment]
Fix package moved
